name: Build And Tests

on:
  push:
    branches:
      - development
    paths:
      - '**/*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.xaml.cs'
      - '**/*.resx'
      - '**/*.pubxml'
      - '**/*.json'
      - '**/*.config'
      - '**/*.manifest'
  pull_request:
    branches:
      - development
    paths:
      - '**/*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.xaml.cs'
      - '**/*.resx'
      - '**/*.pubxml'
      - '**/*.json'
      - '**/*.config'
      - '**/*.manifest'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages
        run: |
          cd "${{ github.workspace }}"
          dotnet restore mfsappscontrol.sln

      - name: Build and publish self-contained app
        run: |
          cd "${{ github.workspace }}"
          dotnet publish mfsappscontrol.sln -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

      - name: Zip build output
        run: |
          Compress-Archive -Path "${{ github.workspace }}\MFSAppsControl\bin\Release\net9.0-windows10.0.22621.0\win-x64\publish\*" -DestinationPath MFSAppsControl.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: mfsappscontrol-zip
          path: "${{ github.workspace }}\\MFSAppsControl.zip"

      - name: Generate release note
        run: |
          cd "${{ github.workspace }}"
          $lines = Get-Content CHANGELOG.md
          $startIndex = ($lines | Select-String -Pattern '^## \[' | Select-Object -First 1).LineNumber - 1
          $nextIndex = ($lines | Select-String -Pattern '^## \[' | Select-Object -Skip 1 -First 1).LineNumber - 1
          $releaseNote = $lines[$startIndex..$nextIndex] -join "`n" 
          $releaseNote | Out-File -FilePath RELEASENOTE.md

