name: Build And Tests

on:
  push:
    branches:
      - development
    paths:
      - '**/*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.xaml.cs'
      - '**/*.resx'
      - '**/*.pubxml'
      - '**/*.json'
      - '**/*.config'
      - '**/*.manifest'
  pull_request:
    branches:
      - main
      - development
    paths:
      - '**/*.sln'
      - '**/*.csproj'
      - '**/*.cs'
      - '**/*.xaml'
      - '**/*.xaml.cs'
      - '**/*.resx'
      - '**/*.pubxml'
      - '**/*.json'
      - '**/*.config'
      - '**/*.manifest'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: ${{ (github.event_name == 'push' && github.actor == 'stevealexandre') || (github.event_name == 'pull_request' && github.actor != 'stevealexandre') }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build and publish self-contained app
        run: |
          cd "${{ github.workspace }}\MFSAppsControl"
          dotnet publish "MFSAppsControl.csproj" -p:PublishProfile=win-x64

      - name: Compress build
        run: |
          Compress-Archive -Path "${{ github.workspace }}\MFSAppsControl\bin\Publish\*" -DestinationPath MFSAppsControl.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: mfsappscontrol-zip
          path: "${{ github.workspace }}\\MFSAppsControl.zip"
